import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Footer } from "./components/sections/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Navbar = () => {
  return (
    <header className="z-10 absolute flex flex-row justify-between px-6 lg:px-10 py-7 lg:py-2 2xl:py-4 w-full">
      {/* {left-side menu here} */}
      {/* Icon  */}
      <div className="hidden lg:flex flex-row lg:gap-10 text-white 2xl:text-md text-lg">
        <Image
          src="/branding/isotipo.svg"
          alt="isotipo.svg"
          height={40}
          width={40}
          className=""
        />

        <span className="my-auto w-fit h-min align-middle">Nosotros</span>
        <span className="my-auto w-fit h-min align-middle">Rutas</span>
        <span className="my-auto w-fit h-min align-middle">Casos</span>
        <span className="my-auto w-fit h-min align-middle">Contacto</span>
        <span className="my-auto w-fit h-min align-middle">Método</span>
      </div>

      {/* {burger button here} */}
      <svg
        className="lg:hidden p-1 border border-primary2-500 rounded-sm h-full"
        viewBox="0 0 100 100"
        preserveAspectRatio="none"
        height={40}
        width={40}
      >
        <path
          d=" M 20,30 h 60 m-60,20 h60 m-60,20 h60"
          stroke="white"
          strokeWidth={10}
        />
      </svg>

      {/* {right-side menu here} */}
      <div className="hidden lg:flex flex-row gap-5 2xl:text-2xl">
        <p className="flex flex-row gap-5 bg-primary2-500 my-auto px-5 2xl:px-7 py-2 lg:border border-primary2-100 2xl:border-2 rounded-full w-fit h-full text-white">
          <Image
            src="/navbar/mx.svg"
            alt="platiquemos"
            width={50}
            height={50}
            className="my-auto w-auto h-7 2xl:h-10"
          />
          <span className="my-auto w-fit h-min font-bold align-middle">ES</span>
        </p>
        <p className="flex flex-row gap-5 bg-primary2-500 my-auto px-5 2xl:px-7 py-2 lg:border border-primary2-100 2xl:border-2 rounded-full w-fit h-full text-white">
          <span className="my-auto w-fit h-min align-middle">PLATIQUEMOS</span>
          <Image
            src="/navbar/whatsapp.svg"
            alt="platiquemos"
            width={50}
            height={50}
            className="my-auto w-auto h-7 2xl:h-10"
          />
        </p>
      </div>
    </header>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black relative`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
